### ISSUE TITLE
Streamline views into observed styled-components

### ISSUE THREAD

**Issue by andraz** [mobxjs/mobx-state-tree#988] opened 2018-08-24 09:24 UTC
```
  .views(todo =>
    observers({
      TextButton: () => (
        <Button onClick={todo.toggle}>{todo.textButtonText}</Button>
      ),
      CountButton: () => (
        <Button onClick={todo.toggle}>{todo.countButtonText}</Button>
      )
    })
  )
```

* [x] I think something is not working as it should.
  * [x] I've checked documentation and searched for existing issues
  * [x] I've made sure your project is based on the latest MST version
  * [x] Minimal reproduction. 
https://codesandbox.io/s/github/andraz/mobx-styled-observers/tree/master/
  * [x] Describe expected behavior
View should detect and decorate all styled components with an observer without a helper function. 
  * [x] Describe observed behavior
At the moment a custom HOC needs to apply observer to each view. 

View() inside mobx-state-tree could get duplicated into styledView() or observableView(), as view needs to be used twice to neatly separate components from calculated fields. This could also be an addon or plugin for MST.

* [x] Feature request
   * [x] Describe the feature and why you feel your feature needs to be generically solved inside MST

It would add a great incentive to use MST as a part of a bigger pattern, where store, views and components (all internal workings) are placed together where they belong.

Support for the demonstrated pattern would be especially welcome for beginners as it is very intuitive:
* Root App component gets rendered without any need for wrappers, passing of stores etc. It _just works_.
* A store becomes a self contained _plug and play_ collection of components.
* Design concerns are separated in separate files, so any designer could tweak them.

```
import styled from 'styled-components'

export default styled.button`
  display: block;
  width: 100%;
  height: 30px;
`

**Comment by xaviergonz** [comment] 2018-08-24 09:39
hi!
if the issue is about having to call views twice then please check/comment on https://github.com/mobxjs/mobx-state-tree/issues/982

if the issue is about having to call observers once per each functional component (observers function) then IMHO that doesn't belong into mobx-state-tree itself (which about state but framework agnostic), but could certainly fit into mobx-react

**Comment by andraz** [comment] 2018-08-24 09:44
Issue is about this part of the code: 
```.views(todo =>
    observers({```

At the moment a HOC "observers" needs to be wrapped around the object and then placed inside views() to make it work.

I am opening this issue about what options do we have and which one could be the optimal way to seamlessly integrate this into MobX ecosystem.

**Comment by k-g-a** [comment] 2018-08-27 16:39
Hello!
You're trying to hold view (react components) inside your model. 
I'd call such coupling an anti-pattern, because: 
- this makes your model (data layer) depend upon your views (representation layer), but it's designed to be conversely: 
  - model is the raw data recieved from and given to "the outher world" (it's sometimes also referred as DTO - data transfer object)
  - in case of MST models also embrace most part of business logic (due to volatile state and computed properties; upcoming watchers will help MST to fulfill this role even more); this layer is often referred as "view model"; this abstractions allows to cover logic with fast and versatile unit tests, which you won't need to fix every time your designer desides to trade link for button;
  - views are built upon that data and may change or even co-exist upon same data;
- this forces you to use either programmatic rendering (ReactDOM.render(React.createElement(...), ...)) or destructuring (``` const {TextButton, CountButton} = modelInstance; ```): first one throws one of react's strongest pros - jsx syntax - away, latter one deminishes abilities to reafactor due to weak IDE support.

May you be mislead by the name ```views```? 
It's actually referring to computed properties as described [in docs](https://github.com/mobxjs/mobx-state-tree#views)

For the case you really want to store you views inside the model, you should wrap those in ```@observable``` from mobx-react either within views:
```javascript
.views(todo =>
      TextButton: () => (
        observable(<Button onClick={todo.toggle}>{todo.textButtonText}</Button>)
      ),
      CountButton: () => (
        observable(<Button onClick={todo.toggle}>{todo.countButtonText}</Button>)
      )
  )
```
or in your consuming component.

**Comment by andraz** [comment] 2018-08-27 17:32
The observables HOC is at the moment doing exactly that, wrapping each of the view functions into an observable, so it does not need to be done manually for each one.

I agree that this belongs more in the mobx-react realm than MST. 

With this simple action, you remove the need for all injecting, passing props, etc... it greatly simplifies the usage on "the other side" of the application outside of store, which deals with DOM.

Computed property can return any value, string, integer, array, function... which includes React modules. It is just a more complex representation of the state (on the computed value output side) built in such a way, that it can return JSX without any props - working "automagically" with access to all store properties including actions already built-in via closure.

If this (returning function) breaks memoization on the computed "return" level (breaking one of the main benefits of computed fields) and returns something which would cause re-renders, please advise how could we avoid such problems.

As demo on the link mentioned above
(https://codesandbox.io/s/github/andraz/mobx-styled-observers/tree/master/)
demonstrates, JSX supports usage in the shape as they get returned from the store.

```
return <store.TextButton />
```
&
```
const { TextButton } = store
return <TextButton />
```
Also the names of both are "Button" when opened in React devtools, so it does not make a difference there.

Testing can be done on the first view() where computed properties are strings, the second view() that uses HOC (and then just wraps the computed properties into styled components) does not need testing, it gets tested if it works on the DOM level (visual regression tests).

```
  .views(todo => ({
    get doneCheck() {
      return todo.done ? '✔️' : '❌'
    },
    get donePlay() {
      return todo.done ? '⏸️' : '▶️'
    },
    get textButtonText() {
      return `${todo.text} | play = ${todo.doneCheck}`
    },
    get countButtonText() {
      return `${todo.donePlay} ${todo.count}`
    }
  }))
  .views(todo =>
    observers({
      TextButton: () => (
        <Button onClick={todo.toggle}>{todo.textButtonText}</Button>
      ),
      CountButton: () => (
        <Button onClick={todo.toggle}>{todo.countButtonText}</Button>
      )
    })
  )
```

**Comment by xaviergonz** [comment] 2018-09-15 09:51
marking as won't fix since it encourages coupling state with UI, which would be an anti-pattern as @k-g-a mentioned (sorry!)

**Closed by xaviergonz** 2018-09-15 09:51 UTC
Labels: brainstorming/wild idea
