### ISSUE TITLE
[enhancement] Pass props to afterCreate method or initialize volatile props from create?

### ISSUE THREAD

**Issue by aksonov** [mobxjs/mobx-state-tree#730] opened 2018-03-24 09:46 UTC
It could be very useful to create some volatile variables by model `create` method. It could be done manually by passing create params to `afterCreate` action OR set volatile properties automatically...

**Comment by Bnaya** [comment] 2018-03-24 20:47
Seems like duplicate of #574

**Comment by mweststrate** [comment] 2018-07-12 11:44
Passing properties during create is not supported as it breaks constructory replayability, so either environments should be used, or manually invoking actions after create to bring your model in the right state are fine

**Closed by mweststrate** 2018-07-12 11:44 UTC
