### ISSUE TITLE
Uncaught TypeError: Cannot read property 'name' of undefined

### ISSUE THREAD

**Issue by dadhichankur** [mobxjs/mobx-state-tree#936] opened 2018-07-19 14:28 UTC
I am playing with Mobx state tree to get to understand it better and see if it can be used for a new project we are starting.

I am getting this error "Uncaught TypeError: Cannot read property 'name' of undefined". I have read the documentation and was not able to think what is going wrong. 

I will paste my code for all us to see whether this is a issue or not .

Index.js

```
import React,{Component} from "react";
import ReactDOM from 'react-dom';
import App from "./app";
import Invoice from "../models/Invoice"

const invoice = Invoice.create({currency:'EUR'}) ;

ReactDOM.render(<App invoice={invoice}/>,document.getElementById('root'));

```
app.Js

```
import React,{Component} from "react";
import {observer} from "mobx-react"

class App extends Component
{
    render(){
        const {invoice} = this.props;

        return(
            <div className="container-fluid">Invoicer
            <h1>{invoice.status()} </h1>
            {!invoice.isPaid && <button onClick={invoice.markPaid}>Pay</button>}
            </div>
        );
    }
}

export default observer(App);
```
models / Invoice.js

```
import {types} from "mobx-state-tree";
import ItemList from "./ItemList";

const Invoice  = types.model("Invoice",{
    currency : types.string,
    isPaid:false,
    itemList : types.optional(ItemList,{items:[]})
})
.actions( self => ({
    markPaid(){
     self.isPaid = true;
    }
}))
.views( self => ({

    status(){
        return self.isPaid ? "Paid,Go Home and Enjoy" :"Not Paid,work more and we will think about it";
    }
}));
```

export default Invoice;

ItemList.js

```
import {types} from "mobx-state-tree";
import {Item} from "./Item";

const ItemList = types.model("ItemList",{
    items: types.array(Item)
});

export default ItemList;
```
item.js

```
import {types} from "mobx-state-tree"

const Item = types.model("Item",{
    quantity : types.number,
    price: types.number,
    comodityName: types.string
});

export default Item;
```
There is no error in terminal when compiling with npm. In bundle.js the error is in this line

```
 array: function(e) {
                return new nt(e.name + "[]",e)
            },
```

package.json , I am only pasting it for getting a a idea of versions that are used.

```
"dependencies": {
    "mobx-react": "^5.2.3",
    "mobx-state-tree": "^3.0.0",
    "react": "^16.4.1",
    "react-dom": "^16.4.1",
    "react-router-dom": "^4.3.1"
  },
  "devDependencies": {
    "babel-core": "^6.26.3",
    "babel-loader": "^7.1.5",
    "babel-preset-es2015": "^6.24.1",
    "babel-preset-react": "^6.24.1",
    "babel-preset-stage-2": "^6.24.1",
    "webpack": "^4.16.1",
    "webpack-cli": "^3.0.8",
    "webpack-dev-server": "^3.1.4"
  }
```
What i was expecting was it should not have this error as there is no name property i have introduced.
Any help?

**Comment by jayarjo** [comment] 2018-07-21 11:44
Copy/pasted your  code to a single sandbox: https://codesandbox.io/s/vy40l4rmm3. Seems working?

Btw, wasn't aware that you can initialize model property like that `itemList : types.optional(ItemList,{items:[]})`. Did you take it from a code sample, or came to it yourself?

**Comment by mweststrate** [comment] 2018-07-21 19:43
please explicitly install `mobx`  as dependency @dadhichankur (you should now be getting peer dependency warnings when running an install) and make sure you have the latest version

**Comment by dadhichankur** [comment] 2018-07-23 14:38
thank you guys for posting reply . @jayarjo  it was a way that i show while reading an article and thought to re use it.

@mweststrate  i explicitly installed mobx,which was done earlier too it was missed when i pasted the code.

My currentpackage.json looks like this
```

"dependencies": {
    "mobx": "^5.0.3",
    "mobx-react": "^5.2.3",
    "mobx-state-tree": "^3.0.0",
    "react": "^16.2.0",
    "react-dom": "^16.2.0",
    "react-router-dom": "^4.3.1"
  },
  "devDependencies": {
    "babel-core": "^6.26.3",
    "babel-loader": "^7.1.5",
    "babel-preset-es2015": "^6.24.1",
    "babel-preset-react": "^6.24.1",
    "babel-preset-stage-2": "^6.24.1",
    "webpack": "^4.16.1",
    "webpack-cli": "^3.0.8",
    "webpack-dev-server": "^3.1.4"
  }
```

There are no warnings, However it still givet the same error in chrome Uncaught TypeError: Cannot read property 'name' of undefined. 

As much as i want to use Mobx , this error which could be only specific to me has stopped in making any progress. can you suggest what could be wrong here.

**Comment by mweststrate** [comment] 2018-07-26 08:54
@dadhichankur Do you have the same issue in other browsers? This might also be a browser plugin / devtool issue or something

Please do setup a test repository so that others can verify. I suspect that this issue is not related to the code itself, but to either project setup or browser circumstances.

**Comment by xaviergonz** [comment] 2018-07-29 16:05
I seem to remember I had that issue when I had two different mobx versions running at the same time (I had a warning on the console telling me that) and fixed it by only having one.

**Comment by bjeld** [comment] 2018-07-30 19:06
Im seeing the issue when using types.optional -> and setting default value together with types.enumeration 

example:
size: types.optional( types.enumeration("ButtonActionSizeEnum", ["small", "medium", "large"]),"small")

to avoid this i looked into using preProcessSnapshot to create default values if none were applied when creating the model.

export const ButtonAction = types
  .model("ButtonAction", {
    type: "create",
    variant: types.enumeration("ButtonActionVariantEnum", [
      "text",
      "flat",
      "outlined",
      "contained",
      "raised"
    ]),
    color: types.enumeration("ButtonActionColorEnum", [
      "default",
      "inherit",
      "primary",
      "secondary"
    ]),
    size: types.enumeration("ButtonActionSizeEnum", ["small", "medium", "large"])
  })
  .preProcessSnapshot(snapshot => {
    const variant = snapshot.variant || "raised";
    const color = snapshot.color || "default";
    const size = snapshot.size || "medium";
    return { ...snapshot, variant, color, size };
  });

Works perfect but not sure if preProcessSnapshot were meant for this

**Comment by xaviergonz** [comment] 2018-08-18 10:32
@bjeld I think that is already fixed in 3.2.1

**Comment by mweststrate** [comment] 2018-08-27 17:42
Closing assuming fixed, until proven otherwise :)

**Closed by mweststrate** 2018-08-27 17:42 UTC
Labels: needs reproduction/info

**Comment by kresli** [comment] 2019-01-24 20:39
I just hit the same issue. So far It seems like the cause is circular dependencies in my imports. The source maps doesn't show actual line so that's another indication I guess.

**Comment by kresli** [comment] 2019-01-24 21:12
I can confirm in my case its circular dependency
<img width="482" alt="image" src="https://user-images.githubusercontent.com/3826097/51708807-bcc96880-201c-11e9-8099-cdb4f50b4d72.png">

**Comment by mweststrate** [comment] 2019-01-24 22:13
This might be helpful:
https://twitter.com/svipben/status/1087677150369640448?s=09

Op do 24 jan. 2019 22:12 schreef Eduard Jacko <notifications@github.com>:

**Comment by kresli** [comment] 2019-01-24 22:19
Thanks. Found it a week ago and it’s really very helpful.

**Comment by sandersoeteman** [comment] 2019-12-04 09:26
I'm also running into this, but now the tweet doesn't exist anymore. Could you please include the gist of the tweet in this issue?

**Comment by sandersoeteman** [comment] 2019-12-04 11:36
Fixed it. It was a ordering/timing thing. The type on the right side of the colon was declared after the type that the property was defined on
