### ISSUE TITLE
types.identifier(types.number)

### ISSUE THREAD

**Issue by lonelydatum** [mobxjs/mobx-state-tree#980] opened 2018-08-21 19:47 UTC
types.identifier(types.number)
is giving me an error of 
TypeError: __WEBPACK_IMPORTED_MODULE_3_mobx_state_tree__.a.identifier is not a function

This worked in previous versions ex) "mobx-state-tree": "2.0.5",

Am I now allowed to call identifier as a function anymore? How can I enforce the identifier as a number in the current version "mobx-state-tree": "3.2.3",

Thanks!

**Comment by mweststrate** [comment] 2018-08-21 20:16
See changelog

Op di 21 aug. 2018 21:47 schreef Gar <notifications@github.com>:

**Comment by xaviergonz** [comment] 2018-08-21 21:35
types.identifierNumber if I recall correctly

**Comment by xaviergonz** [comment] 2018-08-21 23:04
well, the problem is that types.identifier is already taken, so it would be kind of hard to override it with a function that prints the error message.

Thanks though for the suggestion! I'll close the issue since it seems resolved

**Closed by xaviergonz** 2018-08-21 23:04 UTC
