### ISSUE TITLE
AddMiddleware and Flow Actions [bug]

### ISSUE THREAD

**Issue by songyu8285** [mobxjs/mobx-state-tree#764] opened 2018-04-11 15:39 UTC
AddMiddleware throws `TypeError: Cannot read property 'done' of undefined` when some flow actions break down.

```
const Store = types.model({}).actions(function (self) {
  return {
    act: flow(function* () {
      // throw some error
    })
  };
});

const store = Store.create();
addMiddleware(store, function (call, next, abort) {
  try {
    next(call);
  }
  catch (e) {
    console.log(e);   // TypeError: Cannot read property 'done' of undefined
  }
});
```

[CodeSandbox here](https://codesandbox.io/s/xvr54j4zzp)

**Comment by xaviergonz** [comment] 2018-08-18 10:41
Duplicate of #933

**Closed by xaviergonz** 2018-08-18 10:41 UTC
Labels: duplicate, not a bug
