### ISSUE TITLE
fail is not defined exception instead of assertion

### ISSUE THREAD

**Issue by Sinled** [mobxjs/mobx-state-tree#1989] opened 2022-12-09 15:42 UTC
**_Bug report_**

* [x] I've checked documentation and searched for existing issues
* [x] I've made sure my project is based on the latest MST version
* [ ] Fork [this](https://codesandbox.io/s/y64pzxj01) code sandbox or another minimal reproduction. 

**Describe the expected behaviour**
https://github.com/mobxjs/mobx-state-tree/blob/master/packages/mobx-state-tree/src/core/node/BaseNode.ts#L166

it seems there is missing `fail` import, 
instead `"assertion failed: cannot finalise the creation of a node that is already dead" ` i receive `fail is not defined` error in my application

**Describe the observed behaviour**
Correct assertion should be thrown

**Comment by coolsoftwaretyler** [comment] 2023-04-08 03:03
Hey @Sinled - do you have a minimum reproduction of the error that you're seeing here?

**Comment by Sinled** [comment] 2023-04-09 18:24
@coolsoftwaretyler  It was 4 months ago, i can't remember exact reproduction.

But if you open this file
https://github.com/mobxjs/mobx-state-tree/blob/master/packages/mobx-state-tree/src/core/node/BaseNode.ts#L166

`fail` function is called, but it is not imported anywhere in the file

but for example here 
https://github.com/mobxjs/mobx-state-tree/blob/master/packages/mobx-state-tree/src/core/node/scalar-node.ts

`fail` function explicitly imported

as i understand it wont work unless `fail` is in global scope?

**Comment by coolsoftwaretyler** [comment] 2023-04-10 03:56
Thanks, @Sinled! That's still quite helpful.

I am going through old issues and triaging, so I appreciate you getting back to me. If you run into it again, a reproduction would be helpful, but it should be easy for us to find this and patch it up with the provided info.

Not sure on the timeline, just getting started with some maintenance here, but I will update this issue as things get prioritized and moved along.

**Comment by coolsoftwaretyler** [comment] 2023-07-24 18:55
Hey @nithinssabu - I'm going to assign this to you [since you asked to get tasked with some smaller bug fixes](https://github.com/mobxjs/mobx-state-tree/issues/2045#issuecomment-1648263158). I'd love to see a PR here that adds a test making sure we throw the correct error, and of course fix the missing import.

Let me know if you've got additional questions. Thanks!

**Comment by coolsoftwaretyler** [comment] 2023-07-24 18:56
Hmm, for whatever reason, GitHub is not letting me assign this to you. See if you can self-assign, @nithinssabu. Otherwise, this comment should serve as info enough to keep folks from doubling work.

**Comment by chakrihacker** [comment] 2023-09-06 15:49
Hey @nithinssabu have you picked this??

**Comment by coolsoftwaretyler** [comment] 2023-12-05 03:01
Hey folks, I ended up needing to fix this in order to [write some tests of the internals](https://github.com/mobxjs/mobx-state-tree/pull/2127). I'm gonna merge that and close this out. Thanks for reporting it and for your initial interest!

**Closed by coolsoftwaretyler** 2023-12-05 03:01 UTC
Labels: bug, help/PR welcome, level: easy
