### ISSUE TITLE
Observable values fail to consistently trigger render when Fast Refresh is enabled on React Native projects.

### ISSUE THREAD

**Issue by MossP** [mobxjs/mobx-state-tree#1429] opened 2019-12-01 02:00 UTC
**_Bug report_**
Observer appears to become broken when Fast Refresh is used on React Native.
Pressing the 'Add' and clear buttons work as expected until a save is detected in the working folder.
Depending on location of the save index.tsx or todolist.tsx one or both of the modules that are being passed props from the observable module stop working. Saving anything in /Models/* again restores functionality (and wipes the store as expected).

In the test project I have nested a few components to help illustrate this with the values they see rendered to the page.

**Versions**
- mobx: 5.15.0
- mobx-react: 6.1.4
- mobx-state-tree: 3.15.0
- react: 16.9.0
- react-native: 0.61.4
- Xcode 11.2.1
- iOS 13.2.2

* [yes] I've checked documentation and searched for existing issues
Other errors similar but the resolutions don't seem to work.
https://github.com/facebook/react-native/issues/26744
https://github.com/mobxjs/mobx-react/issues/784
* [yes] I've made sure my project is based on the latest MST version
* [yes] Minimal reproduction. 

**Sandbox link or minimal reproduction code**
https://github.com/MossP/Fast-Refresh-Mobx-State-Tree-Error

**Describe the expected behavior**
Add Item and Clear Item continue to work after Fast Refresh regardless of which file in the tree was saved.

**Describe the observed behavior**
Store loses binding with visible components. So Add Item and Clear Item no longer trigger renders of the attached observable components.

Thanks for looking at this if you get time.
Moss

PS. Thank you for a great state library. Donation incoming!!!

**Comment by wms** [comment] 2020-01-23 09:36
If it's of any help, I'm currently experiencing what I suspect to be the same issue. The only other piece of information I can offer is that I'm using 'expo' to build the project.

I *think* this may have something to do with the way in which TypeScript sources are being transpiled, as I tried to reproduce this on an idential setup but using vanilla JS and could not. I'll try to get a solid reproduction (or not, as the case may be) to see if it's of any help.

**Comment by wms** [comment] 2020-01-23 12:32
Update the first - this may not be an MST-specific issue; the same behaviour presents itself when using a 'vanilla' mobx observable.

**Comment by coolsoftwaretyler** [comment] 2023-06-30 03:33
Hey @wms - sorry it took so long to get back to you here. It's been a few years, but do you remember if this ever got resolved for you? I see a few issues linked that were closed in React Native and mobx-react.

I'm going to label this issue as needs more info for now. If there's an ongoing bug, I'd love to keep talking about it and get to a root cause. If I don't hear back from you in a week or two, I'll close this out.

**Comment by wms** [comment] 2023-06-30 06:48
Can't speak for the OP, but I've not revisted this since first encountering it. I think whatever minimal reproduction sample I had is long-gone by now, so I have no objection to closing this out. Thanks for checking back in!

**Comment by coolsoftwaretyler** [comment] 2023-06-30 15:10
Thanks @wms! I will keep this open for OP for now but I would guess we'll be closing it out.

**Comment by coolsoftwaretyler** [comment] 2023-07-13 22:52
I think we're gonna close it out here. Thanks, all!

**Closed by coolsoftwaretyler** 2023-07-13 22:52 UTC
Labels: needs reproduction/info
