### ISSUE TITLE
Example mst-example-todomvc crashes when click the destroy (X) button

### ISSUE THREAD

**Issue by asfernandes** [mobxjs/mobx-state-tree#506] opened 2017-11-02 12:30 UTC
```txt
Error: [mobx-state-tree] This object has died and is no longer part of a state tree. It cannot be used anymore.

The object (of type 'AnonymousModel') used to live at '/todos/0'.

It is possible to access the last snapshot of this object using 'getSnapshot', or to create a fresh copy using 'clone'.

If you want to remove an object from the tree without killing it, use 'detach' instead.
```

**Comment by RainerAtSpirit** [comment] 2017-11-15 15:28
A workaround for this would be commenting out/removing `connectReduxDevTools` in https://github.com/mobxjs/mobx-state-tree/blob/090461c84aa60b9b103bf9426534ddcbd821c946/packages/mst-example-todomvc/src/index.js#L43
Not sure if the issue is with `connectReduxDevtools` or with the redux dev tools extension.

**Comment by kindy** [comment] 2018-02-13 09:51
meet same issue in my own project.
seems it's a connectReduxDevtools bug.

**Comment by kindy** [comment] 2018-02-13 10:08
seems it's caused by mst's middleware code: [mobx-state-tree/src/middlewares/on-action.ts#L211](https://github.com/mobxjs/mobx-state-tree/blob/master/packages/mobx-state-tree/src/middlewares/on-action.ts#L211)

for removed node `sourceNode`, call to `getRelativePathBetweenNodes(getStateTreeNode(target), sourceNode)` will throw error.

```js
    function fireListener(rawCall: IMiddlewareEvent) {
        if (rawCall.type === "action" && rawCall.id === rawCall.rootId) {
            const sourceNode = getStateTreeNode(rawCall.context)
            listener({
                name: rawCall.name,
                path: getRelativePathBetweenNodes(getStateTreeNode(target), sourceNode),
                args: rawCall.args.map((arg: any, index: number) =>
                    serializeArgument(sourceNode, rawCall.name, index, arg)
                )
            })
        }
    }
```

**Comment by jayarjo** [comment] 2018-04-10 17:51
I do not use `connectReduxDevtools` (although I planned to), I'm just trying to remove the item from collection. I tried to use `splice` and also MST `destroy` method - both result in the abovementioned error.

**Comment by xaviergonz** [comment] 2018-10-20 21:08
works now (3.7.0), so closing

**Closed by xaviergonz** 2018-10-20 21:08 UTC
Labels: bug, docs or examples, help/PR welcome
