### ISSUE TITLE
Typescript: Invalid or missing properties allowed in some cases of SnapshotIn

### ISSUE THREAD

**Issue by evelant** [mobxjs/mobx-state-tree#1373] opened 2019-08-21 20:56 UTC
**_Bug report_**

* [x ] I've checked documentation and searched for existing issues
* [x ] I've made sure my project is based on the latest MST version
* [x ] Fork [this](https://codesandbox.io/s/y64pzxj01) code sandbox or another minimal reproduction. 

**Sandbox link or minimal reproduction code**
https://codesandbox.io/s/peaceful-greider-2kpsn

**Describe the expected behavior**
SnapshotIn should expect all required properties of the model.

**Describe the observed behavior**
Seems there are two issues here:

1. If a function with an inferred return type returns a SnapshotIn it can return extra properties that don't belong to the model without an error.
2. A SnapshotIn isn't required to have the non-optional properties specified on the model. An empty object will be a valid SnapshotIn.

This makes it difficult to know if my input object for model creation has all the properties it needs.

**Comment by mweststrate** [comment] 2019-10-28 20:10
Might be fixed by #1269

**Comment by mweststrate** [comment] 2019-10-28 20:13
Note that the test cases in the (untyped) form of `() => (` are useless; typescript will always allow additional properties to exist if the object is not coming from a direct constant assignment (because more properties are a valid subtype of what is expected). So, those cases behave as designed. For more details, google for "TypeScript freshness"

**Comment by coolsoftwaretyler** [comment] 2023-06-30 04:13
Hey folks, since there wasn't any activity after the comment about https://github.com/mobxjs/mobx-state-tree/pull/1269, I'm going to mark this to be closed out unless I hear otherwise in the next two weeks or so.

**Comment by coolsoftwaretyler** [comment] 2023-07-13 22:49
It's been about two weeks. Closin' it out!

**Closed by coolsoftwaretyler** 2023-07-13 22:49 UTC
Labels: should be ready to close
