### ISSUE TITLE
computed identifiers based on baseModel

### ISSUE THREAD

**Issue by ArsSirek** [mobxjs/mobx-state-tree#200] opened 2017-06-18 14:55 UTC
Hi! Thanks for the great work, I am very excited, but lack expertise to grasp all ideas (sorry in advance)

Is it possible to compute the identifier dynamically based on other provided properties? 

I am trying to build generic model for Table data, here are simplified example of MST model definitions
I tried to use late, but it obviously didn't work
`

    export const Cell = types.model("Cell",
        {
            get table() {
                return getParent(this).table;
            },
            id: types.late(() => {
                return types.optional(types.identifier(), this.colName + '-' + this.rowId)
            }),
            colName: types.string,
            rowId: types.string,
            value: types.maybe(types.frozen),
            get row() {
                getParent(this);
            },
            column: types.late(() => types.optional(types.reference(Column), this.colName)),
        });
    
    export const Row = types.model("Row",
        {
            get table() {
                return getParent(this);
            },
            tableName: types.string,
            rowId: types.string,
            id: types.late(() => {
                return types.optional(types.identifier(), this.tableName + '-' + this.rowId)
            }),
            cells: types.map(Cell),
            expanded: false,
        });
    
    export const Column = types.model("Column",
        {
            get table() {
                return getParent(this);
            },
            tableName: types.string,
            name: types.string,
            id: types.late(() => {
                return types.optional(types.identifier(), this.tableName + '-' + this.name)
            }),
            sortable: false,
            hidden: false,
            editable: false,
        }, {
            hide(value = true) {
                this.hidden = value;
            },
        });
    
    export const TableModel = types.model("TableModel",
        {
            name: types.identifier(),
            columns: types.optional(types.map(Column), {}),
            rows: types.optional(types.array(Row), []),
    
            get store() {
                return getParent(this);
            },
            get visibleColumns() {
                return this.columns.filter(column => !column.hidden);
            },
        },
    );

`

1) the fields I want to use for identifier construction are all presented in the Object from which the MST model build, is there, or can we introduce a way to get them?
2) recently you introduced "Volatile state" which can be defined  as function from " (instance) => .." is it possible to have similar way to compute optional value, define optional value as function from raw data (initial "Snapshot")?

Or am I doing something completely wrong...

**Comment by mattiamanzati** [comment] 2017-06-19 08:50
Hello! Identifiers are immutable to make reconciliation work correcly, I think that in your case #100 should allow you to preprocess the snapshot and pass down a computed id for the cell! What do you think? :)

**Comment by ArsSirek** [comment] 2017-06-19 19:52
@mattiamanzati thanks for the response! 
Yeah, if I get the idea correctly that will allow me to solves the case. Fine solution.
Can't imagine the exact place for the hook api, though, will it be among actions part as "afterAttach" and "afterCreate" ?

I still like the idea to add an option to pass a function from snapshot to "types.optional" second argument. That seems to me to be a good way to compute defaults for some of the properties. But I understand that this may be unnecessary complication for the library, as it will not solve something like #165 . 

I am fine with any solution you end up with! :) Good luck with the library!

**Comment by mattiamanzati** [comment] 2017-06-19 19:55
Yeah, it will be defined inside model actions, where hooks belongs to :)

**Comment by mattiamanzati** [comment] 2017-06-19 19:57
Note that optional already accepts a function, but it takes no parameter because optional sets the value only if the snapshot for that attribute is undefined, so it isnt able to read the snapshot of the parent :) Will be easier to preprocess the snapshot on the parent :)

**Comment by ArsSirek** [comment] 2017-06-19 21:06
Sorry, wasn't able to build and check, and I haven't yet explored the MST project code in detail, but that note you made, get me curious, wouldn't it be as easy as [this](https://github.com/ArsSirek/mobx-state-tree/commit/9c32f20a44380a0e8e2fdc2169d807fa3589fc5d) than?

**Comment by ArsSirek** [comment] 2017-06-19 21:20
@mattiamanzati Thanks, for the explanation, and please, ignore the question, I get that it's not :) 
I still have much to learn here.. )

**Comment by mattiamanzati** [comment] 2017-06-19 21:31
The problem is that the value is being constructed and snapshot isnt hold, so the most flexiblwe solution is to implement snapshot hooks :)

**Comment by mweststrate** [comment] 2017-06-19 22:08
Yeah I think snapshots hooks are a fine place to solve this, so closing this one in favor of #100 as a solution for this.

P.s. note that in your specific case, you could also express col_name / rowid as computed properties, by splitting the id. Than in the snapshot you just only provide the 'id'. But I admit, that is a bit contrived indeed.

**Closed by mweststrate** 2017-06-19 22:08 UTC

**Comment by mweststrate** [comment] 2017-06-21 18:53
Released snapshot pre-processing in 0.8.0

**Comment by Aakash359** [comment] 2022-07-01 07:10
Error: [mobx-state-tree] default value cannot be an instance, pass a snapshot or a function that creates an instance/snapshot instead,
Can any resolves this issues that is occured in mob-x state tree, i am a new in mob-x so i don't have an idea about
