### ISSUE TITLE
Destroy / Remove Error.

### ISSUE THREAD

**Issue by chobo2** [mobxjs/mobx-state-tree#879] opened 2018-06-17 17:13 UTC
Hi

I been following the egg head tutorials and everytime I get to the destroy part my code fails. I took one of the codepen examples and modified it and I get the same error. 

Am I doing something wrong or is this a bug?

https://codesandbox.io/s/322mz36moq

**Comment by mweststrate** [comment] 2018-06-18 07:53
The problem is 

```javascript
function deleteTodo(d) {
            console.log('fdafadf', d)
            destroy(d)
        }
```

The `console.log` causes the exception here. The reason is that console.log is actually an async operation, so although you invoke the console before the destroy, `d` will only be evaluated and pretty printed when the console flushes in the future. Removing the console statement, or serializing `d` immediately (for example by using `getSnapshot(d)` or even `console.log("fdafadf" + d)` will cause `d` to be 'serialized' immediately and will avoid the exception

(also note the React key warning should be fixed)

**Comment by mweststrate** [comment] 2018-06-18 11:41
Closing question as answer has been provided, feel free to re-open op follow up questions

**Closed by mweststrate** 2018-06-18 11:41 UTC

**Comment by chobo2** [comment] 2018-06-18 15:44
@mweststrate 

Wow I would have not figured out that it is the console.log that is the issue.  Maybe this should be noted in the documentation(not sure if this common knowledge).

I guess if I would have wrapped it in a flow it would have not had that error?
