### ISSUE TITLE
Typcheck doesn't work correctly for instances in production mode

### ISSUE THREAD

**Issue by pedrokohler** [mobxjs/mobx-state-tree#1597] opened 2020-10-28 01:50 UTC
**_Bug report_**

* [X] I've checked documentation and searched for existing issues
* [X] I've made sure my project is based on the latest MST version

**Sandbox link or minimal reproduction code**
https://codesandbox.io/s/funny-fire-xux5i?file=/src/index.js

**Describe the expected behavior**
According to documentation, typecheck should work both for the instance and for the snapshot.

**Describe the observed behavior**
Incorrect data doesn't cause typecheck to throw when using the instance. Since in production mode you can create an instance without any type checks, this can lead to errors in production.

**Comment by coolsoftwaretyler** [comment] 2023-06-28 19:39
Hey @pedrokohler - thanks for filing this issue, and I'm sorry it took so long for anyone to get back to you here.

This is functioning as intended, for performance reasons I believe. If you need typechecks in production that fail, you can use the `typecheck` function directly: https://mobx-state-tree.js.org/API/#typecheck

I'm going to close this out, but if you or other folks really want MST to change this behavior (it would be a breaking change), I encourage you to hop in the [discussions](https://github.com/mobxjs/mobx-state-tree/discussions).

**Closed by coolsoftwaretyler** 2023-06-28 19:39 UTC
