### ISSUE TITLE
Models with snapshotProcessor can't be added to maps

### ISSUE THREAD

**Issue by igaponov** [mobxjs/mobx-state-tree#1506] opened 2020-04-15 06:12 UTC
**_Bug report_**

* [x] I've checked documentation and searched for existing issues
* [x] I've made sure my project is based on the latest MST version
* [x] Fork [this](https://codesandbox.io/s/y64pzxj01) code sandbox or another minimal reproduction. 

**Sandbox link or minimal reproduction code**
https://codesandbox.io/s/mobx-state-tree-todolist-i5idw

**Describe the expected behavior**
Maps should work with processed models without errors.

**Describe the observed behavior**
Adding a processed model throws the next exception:
```
[mobx-state-tree] Error while converting <Todo@<root>(id: 01)> to `Todo`:

    value of type Todo: <Todo@<root>(id: 01)> is not assignable to type: `Todo`, expected an instance of `Todo` or a snapshot like `snapshotProcessor({ id: identifier; title: string; finished: boolean? })` instead. (Note that a snapshot of the provided value is compatible with the targeted type)
```

**Comment by mweststrate** [comment] 2020-04-15 19:48
I think you linked the wrong sandbox? It doesn't seem to contain either a map or a snapshot processor

**Comment by igaponov** [comment] 2020-04-15 20:24
@mweststrate sorry, it didn't save my last changes. Now the link works.

**Comment by mbest** [comment] 2020-04-22 23:37
I'm getting a similar problem:

> Error: [mobx-state-tree] Error while converting <WebFilterSettingsBase@<root>> to `(WebFilterSettingsBase | undefined)`:
    value of type WebFilterSettingsBase: <WebFilterSettingsBase@<root>> is not assignable to type: `(WebFilterSettingsBase | undefined)`, expected an instance of `(WebFilterSettingsBase | undefined)` or a snapshot like `(snapshotProcessor({ allowedList: string[]?; blockedList: string[]?; hasSettings: boolean; isWebsiteFilterEnabled: boolean; useAllowedListOnly: boolean; hasAnyWebsites: boolean; isBlockedBrowsersEnabled: boolean }) | undefined?)` instead. (Note that a snapshot of the provided value is compatible with the targeted type)

This is from simply trying to assign to a `types.maybe(WebFilterSettings)` using `value = WebFilterSettings.create(...)`. Below is the model definition.

```ts
const WebFilterSettingsBase = t.model("WebFilterSettingsBase", {
    allowedList: t.array(t.string),
    blockedList: t.array(t.string),
    hasSettings: t.boolean,
    isWebsiteFilterEnabled: t.boolean,
    useAllowedListOnly: t.boolean,
    hasAnyWebsites: t.boolean,
    isBlockedBrowsersEnabled: t.boolean,
}).actions(self => ({
    setIsWebsiteFilterEnabled: flow(function* setIsWebsiteFilterEnabled(newValue: boolean) {
        const settings = getParentOfType(self, ChildSettingsBase);
        yield setWebsiteFilterToggle(settings.child.userModelIds, newValue);
        self.isBlockedBrowsersEnabled = newValue;
    })
}));

export const WebFilterSettings = t.snapshotProcessor(WebFilterSettingsBase, {
    preProcessor(webFilterSettings: ApiWebFilterSettings) {
        return webFilterSettings as any;
    }
});
```

If you're wondering why I added the `snapshotProcessor`, it's because of the readonly array issue (https://github.com/mobxjs/mobx-state-tree/issues/605#issuecomment-618052315).

**Comment by mbest** [comment] 2020-04-24 02:45
I tried this again after updating to 3.16, and the problem is still there.

**Comment by garrett-gottlieb** [comment] 2020-07-07 07:58
@mweststrate any idea? I have another issue like this too.

**Comment by mweststrate** [comment] 2020-07-07 08:40
No. Build reproductions folks if you want to report something. Closing this issue as the original problem was solved.

**Comment by garrett-gottlieb** [comment] 2020-07-07 17:26
@mweststrate what was the solution?

**Comment by mweststrate** [comment] 2020-07-07 19:31
Sorry, misread the second comment. I don't think there is a solution yet and looks like a bug at first sight.

**Comment by ashitikov** [comment] 2020-10-13 13:36
Same problem. Please review #1581

**Comment by ashitikov** [comment] 2020-11-10 11:56
Any progress on that?

**Comment by jamonholmgren** [comment] 2020-11-17 04:39
@ashitikov I'm taking over as primary maintainer and plan to release #1581 shortly. Note that it will be in version 4.0.x -- if you can't upgrade to v4, I could perhaps do a patch release in 3.x.

**Comment by jamonholmgren** [comment] 2021-01-08 20:16
We actually released #1581 in 5.0.0 just now:

https://github.com/mobxjs/mobx-state-tree/releases/tag/v5.0.0

**Closed by jamonholmgren** 2021-01-08 20:16 UTC
Labels: bug, help/PR welcome
