### ISSUE TITLE
Failed to minify the code from this file

### ISSUE THREAD

**Issue by chemitaxis** [mobxjs/mobx-state-tree#455] opened 2017-10-11 16:51 UTC
Hi, I'm using CRA, and I have this problem with middleware Redux:

```
Failed to minify the code from this file:

 	./node_modules/mobx-state-tree/middleware/redux.js:14

Read more here: http://bit.ly/2tRViJ9
```
This error happens when you run `npm run build` for production.

What about it? Thanks team!

**Comment by chemitaxis** [comment] 2017-10-11 16:52
This is the import:

`import { connectReduxDevtools } from 'mobx-state-tree/middleware/redux';`

**Comment by chemitaxis** [comment] 2017-10-11 16:54
If I do like the example:

https://github.com/mobxjs/mobx-state-tree/blob/e9e804c8c43e1edde4aabbd52675544e2b3a905b/examples/redux-todomvc/src/index.js#L8

I have this error:

> Failed to compile
> ./src/app/App.jsx
> 35:0-20 'mobx-state-tree' does not contain an export named 'connectReduxDevtools'.

**Comment by chemitaxis** [comment] 2017-10-11 17:39
Hi @mattiamanzati and @mweststrate I have created a small project and check the error:

https://github.com/chemitaxis/error_mst_redux

You just need to `clone`, `npm install `and after `npm run build`.

Thanks!

**Comment by mattiamanzati** [comment] 2017-10-11 17:39
Yep, already found out, will be addressed with #446 #445 :)

**Comment by mattiamanzati** [comment] 2017-10-11 17:40
Closing as duplicate of #445 , thanks for reporting! :)

**Closed by mattiamanzati** 2017-10-11 17:40 UTC

**Comment by chemitaxis** [comment] 2017-10-11 17:44
Please tell me when publish it, I will try to update the example TodoMVC Redux to the latest version ;) Best!

**Comment by mattiamanzati** [comment] 2017-10-11 17:46
As workaround, you can just copy the source of that file onto your project for now :)

**Comment by chemitaxis** [comment] 2017-10-11 17:51
I don't know why, but I'm having an issue with the cache or similar, removing folder `node_modules` and `npm install` is not working... same error...  :(

**Comment by chemitaxis** [comment] 2017-10-11 17:57
Oh!! I get the error, the problem is with other library, logRocket ;)
