### ISSUE TITLE
Typescript Examples

### ISSUE THREAD

**Issue by mikecann** [mobxjs/mobx-state-tree#9] opened 2016-12-11 08:46 UTC
I know @mweststrate mentioned in this issue: https://github.com/mobxjs/mobx/issues that better typescript support will be coming soon but I thought I would just start this issue to track my my definite interest in better typing support 😄

**Comment by mquandalle** [comment] 2017-01-31 00:18
So in Typescript, the current `createFactory` example doesn't work because `this` implicitly has type `any` in the methods body. Is anyone aware of a way to write models in Typescript? (I do understand that this project is a work in progress, I'm just curious if someone has found a way, even hacky, to experiment with it in Typescript)

**Comment by mweststrate** [comment] 2017-01-31 06:36
Didn't test, but it is possible in typescript to type this by declaring
this:type as first function arg. Not sure if that helps though as the type
van probably not be named? but maybe that construction can be used to
improve internal types

Op di 31 jan. 2017 01:18 schreef Maxime Quandalle <notifications@github.com

**Comment by mquandalle** [comment] 2017-01-31 11:12
Thank you, I didn't know this "typing this" feature. I haven't found a way to use the types directly defined in the base model but manually creating an interface is working just fine.

**Comment by bradenhs** [comment] 2017-02-21 16:13
The following looks like it's scheduled for the May release of typescript and I'm thinking it should help a lot with this issue: https://github.com/Microsoft/TypeScript/pull/14141

**Comment by mquandalle** [comment] 2017-03-13 11:43
The TypeScript PR implementing `this` typing has been merged and is now usable using `typescript@next` on NPM.

**Comment by Bnaya** [comment] 2017-03-22 12:31
With this keyword there are other issues
use this code
```typescript
import {
  autorun,
  observable,
  reaction,
} from "mobx";
import {
  action,
  createFactory,
  types,
} from "mobx-state-tree";

class ModelSchema {
  public completed = false;
  public id = types.string("");
  public text = types.string("");
  public toggleCompleted = action(function toggleCompleted (this: ModelSchema, completed: boolean) {
    this.completed = completed;
  });
}

// console.log(new ModelSchema());

const sStatic = {
  completed: false,
  id: types.string(""),
  text: types.string(""),
  toggleCompleted: action(function toggleCompleted (this: typeof sStatic, completed: boolean) {
    this.completed = completed;
  }),
};

const schema = new ModelSchema();

const TodoModelTree = createFactory("TodoModel", schema);
const TodoModelTree2 = createFactory("TodoModel2", sStatic);

const t = TodoModelTree();
const t2 = TodoModelTree2();

reaction(() => {
  return t.completed;
}, function cb() {
  console.log('todo is', t.completed)
});

reaction(() => {
  return t2.completed;
}, function cb() {
  console.log('todo2 is', t2.completed)
});


t.toggleCompleted(true);

t2.toggleCompleted(true);

``` 
and see the typescript types error that you get

**Comment by mattiamanzati** [comment] 2017-03-22 13:19
Hello!

types.string("")

should be instead

types.string

I am not able to test it now, but that should fix an issue. If you want to provide a default, you can use types.withDefault(types.string, "")

Let me know if this solves the issue!

**Comment by mquandalle** [comment] 2017-03-24 00:06
I haven't tested with TS 1.3-alpha, but I was previously using type casting like `"" as string` in my models and it was working just fine. Type checking is done at compile time anyway, so why bother using some runtime constructs like `types.string` for the sole role of type safety?

**Comment by mattiamanzati** [comment] 2017-03-24 08:28
Runtime checking is performed mainly in applySnapshot to ensure that the incoming snapshot is valid! :)

**Comment by mweststrate** [comment] 2017-03-29 18:51
closing this one in favor of #66 (feel free to reopen if this one doesn't cover all issues)

**Closed by mweststrate** 2017-03-29 18:51 UTC

**Comment by mquandalle** [comment] 2017-03-31 14:51
I'm trying to see if the new 0.2 API works with typed `this` in object literals in the upcoming typescript 1.3. Here is a simple example:

```typescript
function double(x: number): number {
  return 2 * x;
}

const myModel = types.model({
  x: 0,
  doubleX() {
    return double(this.x);
  }
})
```

This snippet doesn't compile because of the following error in the `doubleX` method:

```
Argument of type 'number | IType<any, number> | (number & IAction)' is not assignable to parameter of type 'number'.
  Type 'IType<any, number>' is not assignable to type 'number'.
```

Is `IType` working as intended here?
