### ISSUE TITLE
if ("get" in descriptor) is blocking from using 'target' as an attribute in my model

### ISSUE THREAD

**Issue by ak-pdeshaies** [mobxjs/mobx-state-tree#1700] opened 2021-04-20 19:25 UTC
I have:

* [x] A conceptual question. 
  * [x] I've checked documentation and searched for existing issues
  * [ ] I tried [GitHub Discussions](https://github.com/mobxjs/mobx-state-tree/discussions) first
* [x] I think something is working as it was coded.
  * [x] But I also think it introduced a regretful side-effect
* [ ] I think something is not working as it should.
  * [ ] I've checked documentation and searched for existing issues
  * [ ] I've made sure your project is based on the latest MST version
  * [ ] Fork [this](https://codesandbox.io/s/jlnmjqr7xv) code sandbox or another minimal reproduction. 
  * [ ] Describe expected behavior
  * [ ] Describe observed behavior
* [ ] Feature request
   * [ ] Describe the feature and why you feel your feature needs to be generically solved inside MST
   * [x] Are you willing to (attempt) a PR?
   
_Not following the above template might result in your issue being closed without further notice_

I upgraded MST from v3.17.2 to v5.0.1 (I know a pretty big step)
I also introduced Typescript into my project.

I'm fairly new to TS so I was assuming I was doing something wrong. after a day or so of digging I came across this lovely bit of code in file `mobx-state-tree/packages/mobx-state-tree/src/types/complex-types/model.ts`

```
        // the user intended to use a view
        const descriptor = Object.getOwnPropertyDescriptor(props, key)!
        if ("get" in descriptor) {
            throw fail("Getters are not supported as properties. Please use views instead")
        }
```

The problem is that I was trying to use an attribute named target :-|

Do you se the problem? ;-)

Maybe we could change the above to (or something similar)
```
        // the user intended to use a view
        const descriptor = Object.getOwnPropertyDescriptor(props, key)!
        if (descriptor.match(/^get /i)) {
            throw fail("Getters are not supported as properties. Please use views instead")
        }
```
I know descriptor is not a string ;-) but you get the idea.

**Comment by coolsoftwaretyler** [comment] 2023-06-28 03:36
Hey @ak-pdeshaies - thanks for the issue, and I'm sorry it's taken so long for folks to get back to you.

I see what you mean here! That's a sneaky bug. I'm going to label this as a bug and hopefully we can get working on a fix. 

I know it's a been a while, and if you've since moved on past the problem, I totally understand. But if you have time, it would help us out a lot if you could write up a reproduction of the issue.

If you're uninterested, we'll find time eventually to get to it. But we'd welcome the repro/a PR to help fix.

**Comment by ak-pdeshaies** [comment] 2023-06-28 12:29
Hello!

Wow! It's been a while indeed ;-) 

Let me throw something up on codesandbox and try to reproduce. :fingers-crossed: end of day tomorrow

**Comment by coolsoftwaretyler** [comment] 2023-07-23 04:01
Hey @ak-pdeshaies - I am working on a related part of the codebase and tried to reproduce your original bug, but everything seems to be working. Here's some code:

```ts
import { types, getSnapshot } from "mobx-state-tree";

const Tweet = types.model("Tweet", {
  body: types.string,
  target: false
});

const TwitterStore = types.model("TwitterStore", {
  tweets: types.array(Tweet)
});

const twitterStore = TwitterStore.create({
  tweets: [
    {
      body: "Anyone tried MST?"
    }
  ]
});

const snapshot = getSnapshot(twitterStore);

console.log(snapshot);
```

Sandbox: https://codesandbox.io/s/modest-shaw-f94h5m?file=/src/index.ts

No errors, TypeScript or otherwise.

Did I misunderstand the original issue? Or perhaps this got fixed in the interim.

**Comment by ak-pdeshaies** [comment] 2023-07-24 14:58
Hey Tyler,

I didn't get a chance yet to try and repro. I'm in a pretty big crunch to
deploy something big on my end.

You *ARE* on my todo and I *WILL* get to it soon(ish)

Thanks
pd

**Comment by coolsoftwaretyler** [comment] 2023-07-24 17:36
All good @ak-pdeshaies! I am not in a rush, especially since I think the issue got solved at some point, haha.

I'll keep this open for now, but if you don't get around to it in a few weeks, I may close it out just to clean up (happy to reopen with a reproduction, of course!)

**Comment by chakrihacker** [comment] 2023-09-06 15:55
Hey @ak-pdeshaies and @coolsoftwaretyler I was playing with your codesandbox and trying to reproduce, but couldn't do it. I feel we can close this for now and in case if it's reproduced we can reopen this

**Comment by coolsoftwaretyler** [comment] 2023-09-07 03:53
Thanks for catching this, @chakrihacker - I agree. Been a while.

@ak-pdeshaies - I'm going to close this for now, but happy to reopen with a reproduction.

Thanks, all!

**Closed by coolsoftwaretyler** 2023-09-07 03:53 UTC
Labels: bug, needs reproduction/info, help/PR welcome, level: easy
