### ISSUE TITLE
Broken model types in 6.0.0 version

### ISSUE THREAD

**Issue by dfilatov** [mobxjs/mobx-state-tree#2186] opened 2024-06-28 12:13 UTC
**_Bug report_**

-   [x] I've checked documentation and searched for existing issues [and discussions](https://github.com/mobxjs/mobx-state-tree/discussions)
-   [x] I've made sure my project is based on the latest MST version
-   [x] Fork [this](https://codesandbox.io/s/y64pzxj01) code sandbox or another minimal reproduction.

**Sandbox link or minimal reproduction code**

```ts
const BaseModel = types.model();
type BaseModelType = typeof BaseModel;

const DerivedModel = BaseModel.props({ a: '' });

const test: BaseModelType = DerivedModel;
```

**Describe the expected behavior**

No type errors

**Describe the observed behavior**

```
Type 'IModelType<{ a: IType<string | undefined, string, string>; }, {}, _NotCustomized, _NotCustomized>' is not assignable to type 'IModelType<{}, {}, _NotCustomized, _NotCustomized>'.
  The types of 'views(...).CreationType' are incompatible between these types.
    Type 'ModelCreationType<ExtractCFromProps<{ a: IType<string | undefined, string, string>; }>>' has no properties in common with type 'IStateTreeNode<IAnyType>'.ts(2322)
```

It has been broken in 6.0.0 version. It works in 5.4.1 version as expected.

**Comment by coolsoftwaretyler** [comment] 2024-06-28 13:07
Thanks for the bug report @dfilatov! Sorry for the inconvenience. I will look into this soon.

**Comment by coolsoftwaretyler** [comment] 2024-06-28 14:17
Hi @dfilatov - what TypeScript version are you using? I'm having trouble reproducing. Here's a CodeSandbox without errors: https://codesandbox.io/p/sandbox/issue-2186-reproduction-dgy9g3

Version 6.0.0 upgraded TypeScript to `5.3.3` which seems a possible culprit if you're seeing issues locally.

**Comment by dfilatov** [comment] 2024-06-28 14:19
> Hi @dfilatov - what TypeScript version are you using?

5.4.5

**Comment by dfilatov** [comment] 2024-06-28 14:21
I've opened your link and see error:

<img width="879" alt="image" src="https://github.com/mobxjs/mobx-state-tree/assets/67957/81c920cf-ebe1-490f-a0ae-2515d49688e2">

**Comment by coolsoftwaretyler** [comment] 2024-06-28 14:30
Oh nice. Must have been a bug on CodeSandbox.

Will continue investigating!

**Comment by coolsoftwaretyler** [comment] 2024-07-01 00:29
I ran [git bisect](https://git-scm.com/docs/git-bisect) on the reproduction code you provided and it identified 46334b6d37a9fa9b9b984a07a0689391381909a3 as the commit that introduced the error.

I wonder if `WithAdditionalProperties` here: https://github.com/mobxjs/mobx-state-tree/commit/46334b6d37a9fa9b9b984a07a0689391381909a3#diff-8ce65433bb1651566fa2253bfc8167953b5871ef77ed073d1d47d0e4876fabdcR217 is the culprit?

Will keep investigating!

**Comment by coolsoftwaretyler** [comment] 2024-07-01 00:39
Ok, looks like the issue is with `ModelCreationType2` and its changes. Here is a commit that fixes your reported issue: https://github.com/mobxjs/mobx-state-tree/pull/2187/commits/86c8cf374a6f0a01425df100987597db1095e09f#diff-8ce65433bb1651566fa2253bfc8167953b5871ef77ed073d1d47d0e4876fabdcR139 (it's a little big because I'm on a new machine that doesn't seem to respect our formatting right now, my bad), but it causes other type specifications in the test suite to fail.

@dfilatov - are you only encountering this issue specifically when you create a base model with no properties? I want to figure out if this is happening because empty models are a special case or if there's a bigger problem with the `props` builder on models.

Let me know!

**Comment by dfilatov** [comment] 2024-07-01 20:07
> @dfilatov - are you only encountering this issue specifically when you create a base model with no properties?

yep, looks like it's happened with base models without own props (but with own actions/views)

**Comment by coolsoftwaretyler** [comment] 2024-07-01 20:55
Very helpful! I think we just need to figure out some way to carve out the types to accommodate a model like that. 

As a stopgap while we figure it out, I might suggest adding some kind of placeholder property in that model definition to clear the error if you don't want to ts-ignore/ts-expect-error

**Comment by coolsoftwaretyler** [comment] 2024-07-05 02:36
The root of the problem is, I believe, here:

```ts
export type ModelCreationType2<P extends ModelProperties, CustomC> = keyof P extends never
  ? // When there are no props, we want to prevent passing in any object. We have two objects we want to allow:
  //  1. The empty object
  //  2. An instance of this model
  //
  // The `IStateTreeNode` interface allows both. For (1), these props are optional so an empty object is allowed.
  // For (2), an instance will contain these two props, including the "secret" `$stateTreeNodeType` prop. TypeScript's
  // excess property checking will then ensure no other props are passed in.
  IStateTreeNode
  : _CustomOrOther<CustomC, ModelCreationType<ExtractCFromProps<P>>>
```

Introduced here: https://github.com/mobxjs/mobx-state-tree/commit/46334b6d37a9fa9b9b984a07a0689391381909a3#diff-8ce65433bb1651566fa2253bfc8167953b5871ef77ed073d1d47d0e4876fabdcR139

If we go back to the old definition of `ModelCreationType2`, [these tests](https://github.com/mobxjs/mobx-state-tree/commit/46334b6d37a9fa9b9b984a07a0689391381909a3#diff-6086a7b504c321f08095f9b5dad311c73ba2f27e6c85ddc9bfa2bf4a091f091eR1173) begin failing, which I think may be a worse state, because it would allow people to instantiate models with non-existent properties without TypeScript warning them of an issue there.

I brought this up in the maintainers' Discord channel because I'm not sure how to reconcile the old behavior with the new. If anyone out there has a good TypeScript idea, let me know.

**Comment by coolsoftwaretyler** [comment] 2024-07-05 02:43
There is one workaround that exists today. If you use the `Instance` type alias on `typeof BaseModel`, TypeScript is happy about it:

```
  const BaseModel = types.model()
  type BaseModelType = Instance<typeof BaseModel>

  const DerivedModel = BaseModel.props({ a: "" })

  const test: BaseModelType = DerivedModel
  ```

Here's no red lines in VS Code:

![Screenshot 2024-07-04 at 8 43 22 PM](https://github.com/mobxjs/mobx-state-tree/assets/29899554/5d57b897-c044-4edb-b842-e722f40b5fd2)

**Comment by coolsoftwaretyler** [comment] 2024-07-05 02:59
I suppose it isn't exactly correct to say that this is an Instance, since it's an extension of the definition.

Still, this makes me think we can maintain the TypeScript changes from 6.0.0 and make another type alias available that you can use to opt into the second clause of the conditional type. I will think some more on it but this feels like a viable path forward.

**Comment by thegedge** [comment] 2024-07-05 13:55
> I suppose it isn't exactly correct to say that this is an Instance, since it's an extension of the definition.

💯

I do think this should be permitted. I'll try to get this fixed sometime this weekend and make sure we expand the test suite for types.

Thanks for the report, @dfilatov!

**Comment by coolsoftwaretyler** [comment] 2024-07-06 03:37
Should be fixed in https://github.com/mobxjs/mobx-state-tree/pull/2189, which I'll merge and release sometime this weekend or early next week.

**Comment by coolsoftwaretyler** [comment] 2024-07-07 18:40
Just merged! This will be out in a patch release soon.

**Closed** 2024-07-07 18:39 UTC
Labels: bug, Typescript

**Comment by dfilatov** [comment] 2024-07-07 18:47
> Just merged! This will be out in a patch release soon.

Great, thank you!
