### ISSUE TITLE
Self reference model with Typescript and MST v3

### ISSUE THREAD

**Issue by AndrewSorokin** [mobxjs/mobx-state-tree#943] opened 2018-07-23 07:39 UTC
I have some issue with explicit model typing in v3.

I need to get model with self reference with typescript.
There is solution https://github.com/mobxjs/mobx-state-tree/issues/417 for MST v2 smth. like that:
```

interface IModel {
    key: string;
    reference: IModel;

    prop: number;
}
```

```
export const Model: IModelType<ISnapshottable<IModel>, IModel> = types.model({
    key: types.identifier,
    reference: types.late(() => Model),

    prop: types.number
})

```
What is a proper way to express model type with MST v3?

**Comment by AndrewSorokin** [comment] 2018-07-23 11:21
The only ugly way I  was able to do this is there:

`
import {
    types, IModelType, IComplexType
} from 'mobx-state-tree';

const ModelProps = {
    key: types.identifier,
    num: types.number,
    ref: types.frozen() as IComplexType<IModel | string | number, string | number, IModel>,
};


interface IModel {
    method: (param: number) => string, 

    key: string,
    num: number,
    ref: IModel,
}


export const Model: IModelType<typeof ModelProps, IModel> = types.model({
            ...ModelProps,
            ref: types.reference(types.late(() => Model))
        })
    .actions(self => ({
        method: (t: number) => { return t.toString(); }
    }))

export const m = Model.create({
    key: '1',
    num: 0,
    ref: '1'
});
`

**Comment by AndrewSorokin** [comment] 2018-07-24 07:44
Another aproach is to manualy resolve references. 

Still waiting for comments.

```
import {
    types, getRoot, resolveIdentifier
} from 'mobx-state-tree';



export const Model = types.model(
        {
            key: types.identifier,
            num: types.number,
            refKey: types.string
        })
        .views(self => ({
            get ref() {
                const root = getRoot(self);
                const ref = resolveIdentifier(Model , root, self.refKey);
                return ref as typeof Model.Type;
            }
        }))
    .actions(self => ({
        method: (t: number) => { 
            return t.toString(); 
        }
    }))

export const m = Model.create({
    key: '1',
    num: 0,
    refKey: '1'
});

```

**Comment by mweststrate** [comment] 2018-07-25 17:45
Could you create a TS based code sandbox so that others can chime in?

Op di 24 jul. 2018 09:44 schreef AndrewSorokin <notifications@github.com>:

**Comment by AndrewSorokin** [comment] 2018-07-26 12:46
Sure, here is it.

https://codesandbox.io/s/20wlz7256j 

Is there any way to explicilly define model type with self reference?

**Comment by mweststrate** [comment] 2018-07-26 13:07
There seems to be no clean way to fix, as TS really can't handle the type of something self referring. Even upcasting doesn't work. However, using a temporary variable seems to work around it:

```typescript
let tmp: any

///  BrokenTypingsModel has any type or leads to TS compiler error
const BrokenTypingsModel = types.model({
    key: types.identifier,
    brokenRef: types.maybe(types.reference(types.late<BrokenTypeLike, BrokenTypeLike, BrokenTypeLike>(() => tmp)))
})

interface BrokenTypeLike {
    key: string
    brokenRef: BrokenTypeLike
}
tmp = BrokenTypingsModel

const b = BrokenTypingsModel.create({ key: '3' })
console.log(b.brokenRef ? b.brokenRef.key : 'nothing')
```

https://codesandbox.io/s/nknnl9zl2m

**Comment by bourquep** [comment] 2018-08-16 00:04
Is the problem described [here](https://spectrum.chat/thread/84d67a8c-a9e3-4442-bf08-a26bf3907009) similar to the one described in this issue?

**Comment by mweststrate** [comment] 2018-08-27 17:39
@bourquep no that is a different problem, the issue here is like expressing  a self-referring structure `interface Node { children: Node[] } `. However, the issue you are referring to is actions that refer to their own structural type, which we can express because models are built up in parts (and actions can be defined in local closures first) as described here (not ideal, but possible): https://github.com/mobxjs/mobx-state-tree#typing-self-in-actions-and-views)

**Comment by mweststrate** [comment] 2018-08-27 17:40
Closing as a can't fix at this moment :-(

**Closed by mweststrate** 2018-08-27 17:40 UTC
Labels: can't fix

**Comment by xaviergonz** [comment] 2018-08-27 17:47
actually using 'this' for actions defined in the same scope is also possible (like for views), maybe the readme should be updated with that?

**Comment by mweststrate** [comment] 2018-08-27 18:05
Hmm yes that might be outdated indeed

Op ma 27 aug. 2018 om 19:47 schreef Javier Gonzalez <
notifications@github.com>:

**Comment by nspaeth** [comment] 2018-09-04 01:28
I'm having trouble getting the workarounds using `late` working in newer versions, and the code sandbox examples also don't seem to work with newer versions.

That said, there seems to be a couple of new solutions for circular references using conditional types. See [This Comment](https://github.com/Microsoft/TypeScript/issues/14174#issuecomment-416968050) and [this Comment](https://github.com/Microsoft/TypeScript/pull/24897#issuecomment-401423920) in the TypeScript repo. Would either of these be applicable here?

**Comment by kresli** [comment] 2018-11-28 15:05
I can confirm `late` is broken in TS. At least I didn't found any solution how to properly typesafe. Even inline docs doesn't work https://github.com/mobxjs/mobx-state-tree/blob/f62fe87c9dd7c1655242e4511d921e4858cf8756/packages/mobx-state-tree/src/types/utility-types/late.ts#L104

**Comment by xaviergonz** [comment] 2018-11-28 17:16
I'm not sure if you are using late to fix cicular/self-references, but if so, from the docs:

If you are using TypeScript and you get errors about circular or self-referencing types then you can partially fix it by doing:
```
const Node = types.model({
    x: 5, // as an example
    me: types.maybe(types.late((): IAnyModelType => Node))
})
```
In this case, while "me" will become any, any other properties (such as x) will be strongly typed, so you can typecast the self referencing properties (me in this case) once more to get typings. For example:

```node.((me) as Instance<typeof Node>).x // x here will be number```

**Comment by kresli** [comment] 2018-11-28 21:03
thanks @xaviergonz I hoped there will be a better way. I end up using views
```
const Node = types.model({
    x: 5, 
    me: types.maybe(types.late((): IAnyModelType => Node))
}).views( self => ({
    get meChild() {
        return self.me as Instance<typeof Node>;
    }
}))
```

**Comment by xaviergonz** [comment] 2018-11-28 21:13
Nice trick! Never thought of adding a view afterwards to actually make its type proper again!

**Comment by elie222** [comment] 2019-02-12 15:24
Worth adding this trick to TS FAQ

**Comment by mweststrate** [comment] 2019-02-12 21:45
@elie222 PR welcome!

**Comment by elie222** [comment] 2019-02-12 22:02
Sure. Just had a look here and I see the `Edit on GitHub` link is broken:

https://mobx-state-tree.gitbook.io/docs/faq

Where is the repo for these docs?

**Comment by elie222** [comment] 2019-02-12 22:04
Sorry, will just update the official README

**Comment by elie222** [comment] 2019-02-12 22:10
Ah. I see it's already there :)

https://github.com/mobxjs/mobx-state-tree/blob/master/docs/API/README.md#late

**Comment by cevek** [comment] 2019-06-04 18:09
some possible solution: 
```ts
var User = struct({
    user: () => User,
});

User.user.user.user // ok

function struct<T>(obj: T) {
    return obj as {[P in keyof T]: T[P] extends () => infer R ? R : T[P]};
}
```

**Comment by ArmorDarks** [comment] 2019-11-20 12:23
@kresli Isn't it results in the same error about the self-referenced variable? It's still part of the same declaration, so TS will complain that it can't infer its type, even despite it's in a views clause

**Comment by kresli** [comment] 2019-11-24 11:56
@ArmorDarks No it shouldn't because the model part would complain about circulation. So in the getter you would type model where `me` prop in model is any. therefor there is no circulation.

**Comment by mweststrate** [comment] 2019-11-27 17:37
Please don't reply on closed issues
