### ISSUE TITLE
Error with optional and compose models. Cannot read property 'find' of undefined

### ISSUE THREAD

**Issue by jchamb** [mobxjs/mobx-state-tree#922] opened 2018-07-16 18:58 UTC
I have:
* [x] I think something is not working as it should.
  * [x] I've checked documentation and searched for existing issues
  * [x] I've made sure your project is based on the latest MST version

Updating my code to v3.0 ran into an issue after removing types.optional around my array types. I get the above error anytime I use a composed model. Reproduction of the issue below  

https://codesandbox.io/s/71kz23n6pj

**Comment by mweststrate** [comment] 2018-07-16 19:42
Confirmed, that looks like a bug indeed

**Comment by jchamb** [comment] 2018-07-17 17:06
error is also thrown with optional around enumeration.
`types.optional(types.enumeration("state", ["init", "pending", "done", "error"]), "init")`

**Comment by mweststrate** [comment] 2018-07-26 07:37
Confirmed, fixed by #937. Fix will be released later today

**Comment by mweststrate** [comment] 2018-07-26 12:30
Released as 3.0.2

**Closed by mweststrate** 2018-07-26 12:30 UTC
Labels: bug
