### ISSUE TITLE
Type safety when setting a reference with actions

### ISSUE THREAD

**Issue by lucas-wilmart** [mobxjs/mobx-state-tree#1466] opened 2020-02-04 11:07 UTC
**_Question_**

* [*] I've checked documentation and searched for existing issues
* [*] I tried the [spectrum channel](https://spectrum.chat/?t=dad48299-3dfc-4e10-b6da-9af1e39498a3)

Here's my model

```javascript
export const AccountModel = types.model({
  id: types.identifier,
  username: types.string
})

export const AccountsModel = types.model('Accounts', {
  list: types.array(AccountModel),
  selectedAccount: types.maybeNull(types.reference(AccountModel))
})
```

Here's my actions:

```javascript
.actions(self => {
  return {
    selectAccount(newAccount: IAccountModel) {
      // We select the new account
      self.selectedAccount = newAccount.id // TypeScript Error
  }
})
```

You can see where typescript goes wrong on the "TypeScript Error" line.
I searched a lot through the documentation and the spectrum chat but I the only
way to do this without a typescript warning is by typing `self.selectedAccount = newAccount.id as any` . But it's obviously not very good practice. Any way to do this in a cleaner way ?

If there is I suggest you add it to the documentation since it's a basic need when using mst with TypeScript (it it's not already the case, in that case I'm sorry but I couldn't find it). I found several unanswered topics on spectrum asking for this.

Anyway, thanks for this amazing library I really enjoy using.

**Comment by mweststrate** [comment] 2020-02-04 13:54
Note that you can do just `self.selectedAccount = newAccount` if is a model instance, MST will pick the `id` automatically.

If that doesn't help, please provide a small reproduction in a code sandbox so that others can inspect it :)

**Comment by impulse** [comment] 2020-02-20 10:49
@mweststrate I also have an issue with this and made a minimal sandbox. Would be nice if you could take a look on it and tell me what I do wrong:

https://codesandbox.io/s/mst-set-reference-ts-6kul3

**Comment by mweststrate** [comment] 2020-02-20 11:14
@impulse references are references to things that are stored already somewhere else in the tree. Since that doesn't seem to be the case in your example, I guess you should be using just `currentEntry: types.maybeNull(Entry)`, and not a reference at all. If you have further questions, please open a new issue as this doesn't seem to relate to the current thread.

**Comment by mweststrate** [comment] 2020-02-20 11:14
Also closing this as the original question has been answered.

**Closed by mweststrate** 2020-02-20 11:14 UTC

**Comment by impulse** [comment] 2020-02-21 09:32
I was actually referencing things in the tree, I just overlooked the fact that I need to use an identifier type. Got it fixed, thanks!
